export const FUNNEL_STAGES = [
  {
    id: 'views',
    label: 'Views / Footfall',
    tier: 'TOFU',
    color: '#7C4DFF',
    description: 'Awareness. Eyeballs reached.',
    onlineMetric: 'Video views, page visits, impressions',
    offlineMetric: 'Event footfall, school visit attendance',
    inputChannels: ['instagram', 'youtube', 'meta_ads', 'school_visits', 'guerrilla', 'events'],
  },
  {
    id: 'signup',
    label: 'Signup (Lead Captured)',
    tier: 'MOFU',
    color: '#00BCD4',
    description: 'Name + Phone + City verified. Lead in CRM.',
    mechanism: 'QR scan, VIP pass, playbook download, event registration',
    inputChannels: ['qr_codes', 'landing_pages', 'whatsapp_optin', 'event_registration'],
  },
  {
    id: 'app',
    label: 'Application',
    tier: 'MOFU',
    color: '#00BCD4',
    description: 'Formal application submitted on portal.',
    mechanism: 'Online application form, on-spot application at events',
    inputChannels: ['portal', 'campus_events', 'tele_calling'],
  },
  {
    id: 'cee',
    label: 'CEE (Exam Taken)',
    tier: 'MOFU',
    color: '#00BCD4',
    description: 'Common Entrance Exam completed.',
    mechanism: 'Online proctored exam or test center',
    inputChannels: ['exam_portal', 'test_centers'],
  },
  {
    id: 'interview',
    label: 'Interview',
    tier: 'BOFU',
    color: '#FF9100',
    description: 'Interview round completed.',
    mechanism: 'Video call or on-campus interview',
    inputChannels: ['zoom', 'campus_interview'],
  },
  {
    id: 'admission',
    label: 'Admission (Enrolled)',
    tier: 'BOFU',
    color: '#FF9100',
    description: 'Fee paid, seat confirmed.',
    mechanism: 'Payment gateway, on-spot fee waiver + payment',
    inputChannels: ['payment_portal', 'campus_close'],
  },
];
