export const STATE_PROFILES: Record<string, any> = {
  "Delhi-NCR": {
    language: { primary: "Hindi", secondary: "English", codeSwitch: true },
    jeeIntensity: "EXTREME",
    parentArchetype: "Mixed: Engineer-driven + Business-open",
    studentPsych: "Competitive, status-aware, peer-comparison heavy. Coaching culture strong.",
    pricePerception: "₹8L is moderate — they compare against ₹15-25L private colleges",
    channelMix: { instagram: 0.30, youtube: 0.30, whatsapp: 0.20, offline: 0.15, meta_ads: 0.05 },
    culturalLandmines: ["Don't mock DU/DTU — parents have deep emotional ties", "Status signaling matters heavily"],
    competitors: ["Bennett University", "SRM Delhi-NCR", "Amity", "JIIT Noida"],
    reframeAngle: { hi: "IIT ka rasta hi sirf rasta nahi hai. Builder bano, topper nahi.", en: "Stop chasing ranks. Start building." },
    recommendedPersonas: { student: "S1", parent: "P1" },
    festivals: ["Diwali (Oct-Nov) — ad fatigue, avoid heavy push", "Holi (Mar) — Dead Zone overlap"],
  },
  "Rajasthan": {
    language: { primary: "Hindi", secondary: "Rajasthani (informal)", codeSwitch: true },
    jeeIntensity: "EXTREME (Kota effect)",
    parentArchetype: "Engineer-driven, deeply invested in coaching ecosystem",
    studentPsych: "Kota veterans — exhausted, some bitter, some resilient. Honor-bound families.",
    pricePerception: "₹8L is a stretch — many families spent ₹3-5L on Kota already",
    channelMix: { youtube: 0.45, whatsapp: 0.30, offline: 0.15, instagram: 0.10 },
    culturalLandmines: ["NEVER insult Kota coaching — parents chose it, it's a family decision", "Respect the sacrifice narrative"],
    competitors: ["Manipal Jaipur", "LNMIIT", "State govt colleges"],
    reframeAngle: { hi: "Kota ne mehnat sikhayi. Ab us mehnat ko real tech mein lagao.", en: "Kota taught you grit. Now build with it." },
    recommendedPersonas: { student: "S1", parent: "P1" },
    festivals: ["Gangaur (Mar-Apr) — Dead Zone", "Teej (Jul-Aug) — family focus time"],
  },
  "Maharashtra": {
    language: { primary: "Marathi", secondary: "Hindi/English (urban)", codeSwitch: false },
    jeeIntensity: "HIGH",
    parentArchetype: "Mixed: Business-open in Mumbai/Pune, Engineer-driven in Nagpur/Aurangabad",
    studentPsych: "Startup-curious (Pune/Mumbai ecosystem effect). Pragmatic. Brand-aware.",
    pricePerception: "₹8L is reasonable for Pune/Mumbai parents. Stretch for Tier-2 cities.",
    channelMix: { instagram: 0.35, youtube: 0.25, offline: 0.25, whatsapp: 0.10, linkedin: 0.05 },
    culturalLandmines: ["Don't ignore Marathi — even urban parents appreciate acknowledgment", "Pune parents are quality-snobs"],
    competitors: ["VIT Pune", "Symbiosis", "MIT-WPU", "COEP (govt)"],
    reframeAngle: { mr: "Startup capital madhye tumcha college asa pahije ki tumhi build karta.", en: "You're in the startup capital. Your college should teach you to build." },
    recommendedPersonas: { student: "S2", parent: "P2" },
    festivals: ["Ganesh Chaturthi (Aug-Sep) — high emotion, leverage community", "Gudi Padwa (Mar-Apr) — Dead Zone"],
  },
  "Uttar Pradesh": {
    language: { primary: "Hindi", secondary: "Bhojpuri/Awadhi (regional)", codeSwitch: true },
    jeeIntensity: "EXTREME (highest volume of JEE aspirants)",
    parentArchetype: "Government-job-focused, deeply risk-averse, family-decision-driven",
    studentPsych: "Carries enormous family pressure. Aspirational. Price-sensitive. Success = family honor.",
    pricePerception: "₹8L feels HIGH — needs strong ROI justification. Compare against ₹2-3L state colleges.",
    channelMix: { youtube: 0.50, whatsapp: 0.30, offline: 0.15, instagram: 0.05 },
    culturalLandmines: ["Never condescend about Tier-2/3 city aspirations", "Respect family decision structure — father/elder brother often decides"],
    competitors: ["AKTU colleges", "Amity Lucknow/Noida", "GL Bajaj", "State govt colleges"],
    reframeAngle: { hi: "Sarkari naukri ka intezaar mat karo. Tech mein apna raaj banao. Lucknow se Silicon Valley tak.", en: "Don't wait for a government job. Build your tech empire." },
    recommendedPersonas: { student: "S3", parent: "P4" },
    festivals: ["Chhath Puja (Oct-Nov) — family travel", "Eid — respect, don't schedule over"],
  },
  "Karnataka": {
    language: { primary: "Kannada", secondary: "English (Bengaluru: English-first)", codeSwitch: false },
    jeeIntensity: "MEDIUM (CET/KCET is dominant, not JEE)",
    parentArchetype: "Tech-sector aware (Bengaluru effect), placement ROI focused, pragmatic",
    studentPsych: "Startup ecosystem aware. Peer-validation heavy. Already exposed to tech culture.",
    pricePerception: "₹8L is normal — Bengaluru parents compare against ₹12-20L private colleges",
    channelMix: { instagram: 0.35, linkedin: 0.15, offline: 0.30, youtube: 0.15, meta_ads: 0.05 },
    culturalLandmines: ["Don't ignore Kannada pride outside Bengaluru", "Bengaluru parents are sophisticated — no exaggerated claims"],
    competitors: ["PES University", "RV College", "Christ University", "BMS"],
    reframeAngle: { kn: "Bengaluru already startup capital. Illi kattiri, illi build maadi.", en: "You're already in the startup capital. Build here." },
    recommendedPersonas: { student: "S4", parent: "P3" },
    festivals: ["Dasara (Oct) — Mysore focus, reduced attention in rest of state"],
  },
  "Tamil Nadu": {
    language: { primary: "Tamil", secondary: "English (Chennai: bilingual)", codeSwitch: false },
    jeeIntensity: "LOW-MEDIUM (state board + TNEA pathway dominant, JEE not primary)",
    parentArchetype: "Education-obsessed but state-board oriented. Engineering is default aspiration.",
    studentPsych: "Strong regional identity. Prefer known local brands. English-comfortable but Tamil-proud.",
    pricePerception: "₹8L is HIGH — Anna University/govt colleges are ₹50K-2L. Major justification needed.",
    channelMix: { youtube: 0.40, instagram: 0.25, offline: 0.25, whatsapp: 0.10 },
    culturalLandmines: ["NEVER be Hindi-first in TN — instant rejection", "Respect Tamil medium students", "Don't compare against IITs — compare against local private colleges"],
    competitors: ["VIT Vellore", "SRM Chennai", "SSN", "PSG (Coimbatore)"],
    reframeAngle: { ta: "Traditional engineering college-la enna kadaikum? Real-world la build panra college-la seekunga.", en: "Learn to build real products, not just pass exams." },
    recommendedPersonas: { student: "S2", parent: "P1" },
    festivals: ["Pongal (Jan) — high family time, low ad receptivity"],
  },
  "West Bengal": {
    language: { primary: "Bengali", secondary: "English/Hindi", codeSwitch: true },
    jeeIntensity: "HIGH (WBJEE + JEE both active pathways)",
    parentArchetype: "Education-revering. Intellectual prestige matters. Arts/science equally respected.",
    studentPsych: "Intellectually curious. Values debate and thinking. Less startup-driven, more knowledge-driven.",
    pricePerception: "₹8L is SIGNIFICANT — Jadavpur/Presidency are near-free. Strong ROI case needed.",
    channelMix: { youtube: 0.40, whatsapp: 0.25, offline: 0.20, instagram: 0.15 },
    culturalLandmines: ["Respect Jadavpur/Presidency legacy — never dismiss", "Bengali parents value intellectual prestige over money"],
    competitors: ["Jadavpur University", "KIIT Bhubaneswar", "Heritage Institute", "JIS"],
    reframeAngle: { bn: "Chhatro jara bhabe, tara tokei aar traditional exam-er jonyo toiri hoy na — tara builder howar jonyo toiri hoy.", en: "Students who think aren't trained for exams. They're trained to build." },
    recommendedPersonas: { student: "S2", parent: "P3" },
    festivals: ["Durga Puja (Oct) — COMPLETE shutdown. Zero marketing for 10 days."],
  },
  "Bihar": {
    language: { primary: "Hindi", secondary: "Bhojpuri/Magahi", codeSwitch: true },
    jeeIntensity: "EXTREME (massive migration to Kota/Delhi for coaching)",
    parentArchetype: "Government-job-obsessed. Risk-averse. Education = escape from economic hardship.",
    studentPsych: "Hungry, aspirational, willing to relocate. Family honor at stake. Price-sensitive.",
    pricePerception: "₹8L is VERY HIGH. Scholarship/EMI framing essential. Show clear earning potential.",
    channelMix: { youtube: 0.55, whatsapp: 0.30, offline: 0.10, instagram: 0.05 },
    culturalLandmines: ["Never condescend about Bihar", "Respect the sacrifice families make to send kids for coaching"],
    competitors: ["NIT Patna (aspirational)", "Chandigarh University", "LPU"],
    reframeAngle: { hi: "Bihar se nikle ho, duniya banane ke liye. Sarkari naukri ek raasta hai — tech mein apna raasta khud banao.", en: "You left home to build a future. Build it in tech." },
    recommendedPersonas: { student: "S3", parent: "P4" },
    festivals: ["Chhath Puja (Nov) — sacred family event, zero marketing"],
  },
  "Gujarat": {
    language: { primary: "Gujarati", secondary: "Hindi/English", codeSwitch: true },
    jeeIntensity: "MEDIUM (strong local engineering colleges, business-family alternative paths)",
    parentArchetype: "Business-minded. ROI is natural language. Entrepreneurship respected.",
    studentPsych: "Entrepreneurial by culture. Many come from business families. Less exam-obsessed.",
    pricePerception: "₹8L is acceptable — business families think in investment terms",
    channelMix: { youtube: 0.30, instagram: 0.30, whatsapp: 0.25, offline: 0.15 },
    culturalLandmines: ["Don't undersell entrepreneurship — it's their identity", "Respect Gujarati language in communications"],
    competitors: ["DAIICT", "Nirma University", "PDEU", "LJ University"],
    reframeAngle: { gu: "Business family ma thi aawo chho. College pan business jaevi hovi joiye — build karo, sirf padho nahi.", en: "You come from business. Your college should teach you to build, not just study." },
    recommendedPersonas: { student: "S2", parent: "P3" },
    festivals: ["Navratri (Oct) — 9 nights of celebration. Reduced attention but community opportunity."],
  },
  "Telangana": {
    language: { primary: "Telugu", secondary: "English/Hindi (Hyderabad: trilingual)", codeSwitch: false },
    jeeIntensity: "HIGH (TS EAMCET dominant, JEE secondary)",
    parentArchetype: "Tech-aware (Hyderabad IT corridor effect). Values placements heavily.",
    studentPsych: "Tech-exposed. Hyderabad students are startup-aware. Outside Hyderabad: more traditional.",
    pricePerception: "₹8L is moderate in Hyderabad. High outside. Compare against JNTU (near-free).",
    channelMix: { instagram: 0.30, youtube: 0.35, offline: 0.20, whatsapp: 0.15 },
    culturalLandmines: ["Don't conflate Telangana with Andhra Pradesh — distinct identity post-2014", "Telugu medium students need accessible content"],
    competitors: ["IIIT Hyderabad (aspirational)", "VNR VJIET", "CVR College", "Mahindra University"],
    reframeAngle: { te: "Hyderabad already tech hub. Ikkada build cheyyi, ekkada vere choodu?", en: "Hyderabad is already a tech hub. Where better to learn to build?" },
    recommendedPersonas: { student: "S4", parent: "P1" },
    festivals: ["Bonalu (Jul-Aug) — local, respect scheduling"],
  },
};
