export const PERSONA_STORE = [
  {
    id: 'S1', type: 'student', name: 'Arjun', title: 'The JEE Warrior',
    age: 18, gender: 'M', city: 'Delhi', tier: 'Metro',
    academic: '85-90 percentile JEE. Good but not IIT-good.',
    family: 'Middle-class. Father = senior govt engineer.',
    psychology: 'Exhausted, slightly bitter about coaching mills. Ego intact. Wants respect, not pity.',
    hooks: 'Tech flex, "build > memorize", peer stories of non-IIT success',
    repels: 'Any hint of backup plan, pity, "it\'s okay to fail" tone',
    parentGate: 'Father (P1: Mr. Sharma) compares ₹8L vs ₹2L state college. Demands ROI.',
    decisionStyle: 'Decides in 2-3 weeks post-JEE results if shown clear data.',
    funnelEntry: 'TOFU (YouTube/Instagram) → MOFU (campus visit invite) → BOFU (Open Day)',
    coreFear: 'Being stuck in a mediocre college that leads nowhere',
    coreDesire: 'Proving he can succeed without IIT — on his own terms',
    channelPreference: ['youtube_shorts', 'instagram_reels', 'discord'],
    linkedParent: 'P1',
  },
  {
    id: 'S2', type: 'student', name: 'Priya', title: 'The Pragmatic Builder',
    age: 19, gender: 'F', city: 'Pune', tier: 'Metro',
    academic: 'Decent boards. Skipped JEE. Self-taught coder.',
    family: 'Mother (P2: Mrs. Desai) is supportive but anxious about residential safety.',
    psychology: 'Self-directed, contrarian. Doesn\'t care about brand — cares about learning.',
    hooks: 'Curriculum specifics, project showcases, hackathon wins, startup stories',
    repels: 'Vague "world-class faculty" claims, traditional college imagery',
    parentGate: 'Mother needs safety proof. Female student testimonials. Campus security details.',
    decisionStyle: 'Decides in 1-2 weeks once curriculum is proven real. Mother needs safety.',
    funnelEntry: 'TOFU (tech content) → MOFU (playbook download) → BOFU (campus visit with mother)',
    coreFear: 'Wasting 4 years on theory that doesn\'t translate to real skills',
    coreDesire: 'Building something real — a product, a startup, a portfolio',
    channelPreference: ['instagram', 'github', 'tech_blogs', 'discord'],
    linkedParent: 'P2',
  },
  {
    id: 'S3', type: 'student', name: 'Rahul', title: 'The Confused Follower',
    age: 17, gender: 'M', city: 'Lucknow', tier: 'Tier-2',
    academic: 'Scored poorly on JEE. Parents chose coaching path.',
    family: 'Mother (P4: Mrs. Gupta) trusts Alakh Sir. Father passive.',
    psychology: 'Low confidence, high anxiety, decision paralysis.',
    hooks: 'Simple messaging, clear Year 1 roadmap, safety, structure',
    repels: 'Aggressive/rebellious tone, too much choice, pressure',
    parentGate: '100% parent-gated. Mother decides.',
    decisionStyle: 'As long as mother needs. Will not push back on her decision.',
    funnelEntry: 'Mother sees Alakh Sir (TOFU) → WhatsApp group (MOFU) → Campus visit together (BOFU)',
    coreFear: 'Disappointing his family by not getting into a "good" college',
    coreDesire: 'Stability, a clear path, someone telling him it\'ll be okay',
    channelPreference: ['youtube', 'whatsapp_parent_forward'],
    linkedParent: 'P4',
  },
  {
    id: 'S4', type: 'student', name: 'Meera', title: 'The Content Creator',
    age: 18, gender: 'F', city: 'Bengaluru', tier: 'Metro',
    academic: 'Decent, not exceptional. Bored by traditional paths.',
    family: 'Parents are tech-aware, supportive if convinced.',
    psychology: 'Community-driven. Wants a college that looks cool on her feed.',
    hooks: 'Student ambassador content, campus aesthetics, creator community',
    repels: 'Corporate messaging, stock imagery, boomer ads',
    parentGate: 'Will convince parents herself if excited. Low gate.',
    decisionStyle: 'Fast if vibes are right.',
    funnelEntry: 'Sees creator content (TOFU) → DMs ambassador (MOFU) → Campus content shoot (BOFU)',
    coreFear: 'Ending up in a boring, lifeless college environment',
    coreDesire: 'A college that IS her content — aesthetically, socially, technically',
    channelPreference: ['instagram', 'youtube_shorts', 'discord', 'linkedin'],
    linkedParent: null,
  },
  {
    id: 'P1', type: 'parent', name: 'Mr. Sharma', title: 'The ROI Calculator',
    age: 50, gender: 'M', city: 'Delhi', tier: 'Metro',
    occupation: 'Senior government engineer',
    psychology: 'Pure ROI logic. Every rupee accounted for. Will build Excel comparing options.',
    hooks: 'Placement stats with NUMBERS, salary data, fee-vs-earning, named recruiters',
    repels: 'Vague "holistic development", marketing that looks expensive',
    decisionGate: 'Needs: (1) Placement % > state college, (2) Named companies, (3) First-year salary data',
    bestChannel: 'YouTube detailed video → WhatsApp data PDF → Campus visit',
    linkedStudent: 'S1',
    objection: '₹8L vs ₹2L state college — justify the difference with data.',
  },
  {
    id: 'P2', type: 'parent', name: 'Mrs. Desai', title: 'The Safety-First Mother',
    age: 45, gender: 'F', city: 'Pune', tier: 'Metro',
    occupation: 'Working professional',
    psychology: 'Security-first. Hostel safety, female ratio, medical, CCTV, warden.',
    hooks: 'Safety info, female testimonials, parent community, campus tour video',
    repels: 'Aggressive messaging, party hints, all-male imagery',
    decisionGate: 'Needs: (1) Safety walkthrough, (2) Female parent testimonial, (3) Warden/medical details',
    bestChannel: 'Campus visit (mandatory) → Parent WhatsApp group → Video call with existing parent',
    linkedStudent: 'S2',
    objection: 'Is my daughter safe 500km from home?',
  },
  {
    id: 'P3', type: 'parent', name: 'Mr. Verma', title: 'The Brand Snob',
    age: 52, gender: 'M', city: 'Noida', tier: 'Metro',
    occupation: 'Successful businessman',
    psychology: 'Status-driven. Will only consider IOI if it doesn\'t feel like a downgrade.',
    hooks: 'Alumni success, industry partnerships, infrastructure, media coverage',
    repels: '"Alternative" positioning (reads as "lesser"), budget aesthetics',
    decisionGate: 'Needs: (1) Industry partnerships, (2) Infrastructure comparable to top colleges, (3) Media validation',
    bestChannel: 'LinkedIn → Premium campus event → One-on-one with IOI leadership',
    linkedStudent: null,
    objection: 'My son got into an NIT. Why would he go to IOI?',
  },
  {
    id: 'P4', type: 'parent', name: 'Mrs. Gupta', title: 'The Trusting Follower',
    age: 48, gender: 'F', city: 'Lucknow', tier: 'Tier-2',
    occupation: 'Homemaker',
    psychology: 'Trusts Alakh Sir deeply. Low digital literacy. Word-of-mouth driven.',
    hooks: 'Alakh Sir endorsements, simple Hindi content, local testimonials',
    repels: 'Complex websites, English-heavy content, self-research requirements',
    decisionGate: 'Needs: (1) Alakh Sir says so, (2) Simple fee structure, (3) "Beta safe rahega"',
    bestChannel: 'WhatsApp Hindi content + voice notes → Local referral → Campus visit with hand-holding',
    linkedStudent: 'S3',
    objection: 'Will my son be taken care of? Is this real? Alakh Sir recommended it?',
  },
];
